<?php
/**
 * Blog listing registry — add new posts here to update featured + recent on blog.php.
 * Featured = newest date; same-day tiebreaker = higher sort_order.
 */
return [
    [
        'slug'       => 'blog-erp-vs-excel',
        'title'      => 'ERP vs Excel: Which Is Better for Managing Your Business in 2026?',
        'excerpt'    => 'Compare ERP vs Excel for billing, inventory, accounting, GST, and reporting — and see which approach fits your growing business.',
        'date'       => '2026-08-28',
        'sort_order' => 2,
        'read_min'   => 7,
        'image'      => 'assets/img/blog-erp-vs-excel.jpg',
        'card_image' => 'assets/img/blog-erp-vs-excel-card.jpg',
        'image_webp' => null,
        'alt'        => 'ERP vs Excel: Which Is Better for Your Business',
    ],
    [
        'slug'       => 'blog-10-signs-outgrown-manual-billing-accounting',
        'title'      => '10 Signs Your Business Has Outgrown Manual Billing and Accounting',
        'excerpt'    => 'Discover 10 signs your business has outgrown manual billing and accounting, and learn how ERP and billing software can improve accuracy, efficiency, and growth.',
        'date'       => '2026-08-28',
        'sort_order' => 1,
        'read_min'   => 6,
        'image'      => 'assets/img/blog-10-signs-outgrown-manual-billing-accounting.jpg',
        'card_image' => 'assets/img/blog-10-signs-outgrown-manual-billing-accounting-card.jpg',
        'image_webp' => null,
        'alt'        => '10 Signs You Need Automated Billing Software',
    ],
    [
        'slug'           => 'blog-how-erp-simplifies-accounting',
        'title'          => 'How ERP Simplifies Accounting for Indian Businesses',
        'excerpt'        => 'Discover how ERP software streamlines accounting with automated billing, GST compliance, inventory management, and real-time financial reporting for Indian businesses.',
        'date'           => '2026-08-17',
        'sort_order'     => 6,
        // 'promote_recent' => true,
        'read_min'       => 5,
        'image'          => 'assets/img/blog-how-erp-simplifies-accounting.jpg',
        'image_webp'     => 'assets/img/blog-how-erp-simplifies-accounting.webp',
        'alt'            => 'Professional Indian businesswoman using billing software on a laptop in a modern office',
    ],
    [
        'slug'       => 'blog-complete-guide-gst-e-invoicing-in-india',
        'title'      => 'The Complete Guide to GST E-Invoicing in India',
        'excerpt'    => 'Learn everything about GST e-invoicing in India, including eligibility, benefits, IRN generation, compliance, and how ERP software simplifies e-invoicing.',
        'date'       => '2026-08-04',
        'sort_order' => 1,
        'read_min'   => 7,
        'image'      => 'assets/img/blog-complete-guide-gst-e-invoicing-in-india.jpg',
        'card_image' => 'assets/img/blog-complete-guide-gst-e-invoicing-in-india-card.jpg',
        'image_webp' => 'assets/img/blog-complete-guide-gst-e-invoicing-in-india.webp',
        'alt'        => 'The Complete Guide to GST E-Invoicing in India',
    ],
    [
        'slug'       => 'blog-why-businesses-need-crm-software',
        'title'      => 'Why Businesses Need CRM Software: The Key to Better Customer Relationships and Business Growth',
        'excerpt'    => 'Discover why businesses need CRM software to manage leads, improve customer relationships, increase sales, and grow faster with integrated ERP solution.',
        'date'       => '2026-07-25',
        'sort_order' => 1,
        'read_min'   => 6,
        'image'      => 'assets/img/blog-why-businesses-need-crm-software.jpg',
        'image_webp' => 'assets/img/blog-why-businesses-need-crm-software.webp',
        'alt'        => 'Why Businesses Need CRM Software',
    ],
    [
        'slug'       => 'blog-gst-billing-software-benefits-for-businesses',
        'title'      => 'Unlocking Business Growth: Top Benefits of GST Billing Software in India',
        'excerpt'    => 'Discover how online GST billing software streamlines compliance, automates GSTR-1 and GSTR-3B filings, manages real-time inventory, and scales your business.',
        'date'       => '2026-07-20',
        'sort_order' => 5,
        'read_min'   => 6,
        'image'      => 'assets/img/blog-gst-billing-software-benefits-for-businesses.jpg',
        'image_webp' => 'assets/img/blog-gst-billing-software-benefits-for-businesses.webp',
        'alt'        => 'GST Billing Software Benefits for Businesses',
    ],
    [
        'slug'       => 'blog-e-invoicing-under-gst-guide',
        'title'      => 'E-Invoicing under GST: A Complete Guide for Growing Businesses in India',
        'excerpt'    => 'Learn how e-invoicing works under GST. Understand Invoice Reference Number (IRN) generation, mandatory QR codes, and 1-click e-invoicing with MazERP.',
        'date'       => '2026-07-20',
        'sort_order' => 4,
        'read_min'   => 6,
        'image'      => 'assets/img/blog-e-invoicing-under-gst-guide.jpg',
        'image_webp' => 'assets/img/blog-e-invoicing-under-gst-guide.webp',
        'alt'        => 'E-Invoicing under GST in India',
    ],
    [
        'slug'       => 'blog-top-features-gst-billing-software',
        'title'      => '7 Essential Features to Look for in Modern GST Billing Software',
        'excerpt'    => 'Selecting GST software? Explore key features including auto CGST/SGST/IGST calculation, integrated e-way bills, barcode billing, and GSTR reporting.',
        'date'       => '2026-07-20',
        'sort_order' => 3,
        'read_min'   => 7,
        'image'      => 'assets/img/blog-top-features-gst-billing-software.jpg',
        'image_webp' => 'assets/img/blog-top-features-gst-billing-software.webp',
        'alt'        => '7 Essential Features in GST Billing Software',
    ],
    [
        'slug'       => 'blog-eway-bill-generation-rules-guide',
        'title'      => 'E-Way Bill Rules & Generation: A Complete Compliance Guide',
        'excerpt'    => 'Master E-Way Bill rules for consignments over ₹50,000. Learn distance validity guidelines, penalty prevention, and 1-click auto generation with MazERP.',
        'date'       => '2026-07-20',
        'sort_order' => 2,
        'read_min'   => 6,
        'image'      => 'assets/img/blog-eway-bill-generation-rules-guide.jpg',
        'image_webp' => 'assets/img/blog-eway-bill-generation-rules-guide.webp',
        'alt'        => 'E-Way Bill Rules and Generation Guide',
    ],
    [
        'slug'       => 'blog-gst-billing-software-gstr1-gstr3b-filing',
        'title'      => 'How GST Billing Software Simplifies GSTR-1 and GSTR-3B Filing',
        'excerpt'    => 'Prevent return mismatches and tax notices. Discover how automated GST billing software compiles B2B/B2C sales, HSN summaries, and error-free returns.',
        'date'       => '2026-07-20',
        'sort_order' => 1,
        'read_min'   => 6,
        'image'      => 'assets/img/blog-gst-billing-software-gstr1-gstr3b-filing.jpg',
        'image_webp' => 'assets/img/blog-gst-billing-software-gstr1-gstr3b-filing.webp',
        'alt'        => 'GSTR-1 and GSTR-3B Tax Filing Software',
    ],
    [
        'slug'       => 'blog-tally-vs-cloud-erp-comparison',
        'title'      => 'Tally vs. Cloud ERP: Why Indian SMEs Are Switching',
        'excerpt'    => 'Discover why growing Indian SMEs are migrating from offline desktop tools like Tally to modern, integrated cloud ERP systems for real-time remote business management.',
        'date'       => '2026-07-17',
        'sort_order' => 5,
        'read_min'   => 5,
        'image'      => 'assets/img/blog-tally-vs-cloud-erp-comparison.jpg',
        'image_webp' => 'assets/img/blog-tally-vs-cloud-erp-comparison.webp',
        'alt'        => 'Comparison between traditional desktop bookkeeping and cloud ERP dashboards',
    ],
    [
        'slug'       => 'blog-gstr-reconciliation-automation',
        'title'      => 'How to Automate GST Reconciliations (GSTR-2B)',
        'excerpt'    => 'Say goodbye to mismatch penalties. Learn how integrating ERP software automates GSTR-2B purchase reconciliations and simplifies GST invoicing in India.',
        'date'       => '2026-07-17',
        'sort_order' => 4,
        'read_min'   => 5,
        'image'      => 'assets/img/blog-gstr-reconciliation-automation.jpg',
        'image_webp' => 'assets/img/blog-gstr-reconciliation-automation.webp',
        'alt'        => 'Accountant reconciling purchase records with GSTR-2B returns',
    ],
    [
        'slug'       => 'blog-crm-for-indian-wholesalers',
        'title'      => 'Boosting B2B Sales: CRM for Indian Wholesalers',
        'excerpt'    => 'Discover how CRM integration helps Indian B2B wholesalers manage sales pipelines, track customer purchase histories, and streamline credit limit collections.',
        'date'       => '2026-07-17',
        'sort_order' => 3,
        'read_min'   => 5,
        'image'      => 'assets/img/blog-crm-for-indian-wholesalers.jpg',
        'image_webp' => 'assets/img/blog-crm-for-indian-wholesalers.webp',
        'alt'        => 'Wholesale sales team reviewing client pipeline and deals',
    ],
    [
        'slug'       => 'blog-barcode-billing-software-benefits',
        'title'      => 'Barcode Billing: Speeding Up Supermarket Checkouts',
        'excerpt'    => 'Speed up transaction times and eliminate queue bottlenecks at retail counters using barcode inventory scanners integrated with cloud billing systems.',
        'date'       => '2026-07-17',
        'sort_order' => 2,
        'read_min'   => 5,
        'image'      => 'assets/img/blog-barcode-billing-software-benefits.jpg',
        'image_webp' => 'assets/img/blog-barcode-billing-software-benefits.webp',
        'alt'        => 'Cashier scanning barcode labels at supermarket checkout terminal',
    ],
    [
        'slug'       => 'blog-ecommerce-warehouse-management-best-practices',
        'title'      => 'E-commerce Warehouse Management: 5 Best Practices',
        'excerpt'    => 'Learn the top warehouse management strategies for Indian e-commerce brands, from barcode product routing to automated stock transfer orders.',
        'date'       => '2026-07-17',
        'sort_order' => 1,
        'read_min'   => 5,
        'image'      => 'assets/img/blog-ecommerce-warehouse-management-best-practices.jpg',
        'image_webp' => 'assets/img/blog-ecommerce-warehouse-management-best-practices.webp',
        'alt'        => 'Organized e-commerce warehouse shelves and operator scanning box labels',
    ],
    [
        'slug'       => 'blog-how-erp-software-prevents-stock-loss',
        'title'      => 'How ERP Software Prevents Stock Loss: A Complete Guide',
        'excerpt'    => 'Stock loss is one of the biggest hidden expenses for businesses in India. Discover how modern ERP software eliminates inventory discrepancies, automates alerts, and improves cash flow.',
        'date'       => '2026-07-07',
        'sort_order' => 1,
        'read_min'   => 5,
        'image'      => 'assets/img/blog-prevent-stock-loss.jpg',
        'image_webp' => 'assets/img/blog-prevent-stock-loss.webp',
        'alt'        => 'Two warehouse managers looking at computer screen dashboard displaying logistics and inventory',
    ],
    [
        'slug'       => 'blog-why-inventory-management-is-essential',
        'title'      => 'Why Inventory Management Is Essential for Growing Businesses',
        'excerpt'    => 'Without an efficient inventory system, expanding businesses face stock shortages, excess overheads, and lost sales. Discover how modern inventory software streamlines operations.',
        'date'       => '2026-07-03',
        'sort_order' => 4,
        'read_min'   => 5,
        'image'      => 'assets/img/blog-inventory-management.jpg',
        'image_webp' => 'assets/img/blog-inventory-management.webp',
        'alt'        => 'Warehouse manager using tablet',
    ],
    [
        'slug'       => 'blog-5-common-gst-invoicing-mistakes',
        'title'      => '5 Common GST Invoicing Mistakes Indian Businesses Make',
        'excerpt'    => 'Avoid expensive penalties and tax audit mismatches by fixing these basic errors in your CGST, SGST, and IGST invoice formats today.',
        'date'       => '2026-07-03',
        'sort_order' => 3,
        'read_min'   => 6,
        'image'      => 'assets/img/blog-5-common-gst-invoicing-mistakes.jpg',
        'image_webp' => null,
        'alt'        => 'GST tax invoice and calculator',
    ],
    [
        'slug'       => 'blog-how-cloud-erp-helps-manage-multiple-stores',
        'title'      => 'How a Cloud ERP Helps You Manage Multiple Stores Remotely',
        'excerpt'    => 'Learn how retail entrepreneurs monitor real-time sales, control inventory transfers, and track cashier shifts across branches without leaving home.',
        'date'       => '2026-07-03',
        'sort_order' => 2,
        'read_min'   => 4,
        'image'      => 'assets/img/blog-how-cloud-erp-helps-manage-multiple-stores.jpg',
        'image_webp' => null,
        'alt'        => 'Retail entrepreneur using tablet to manage multiple store sales remotely',
    ],
    [
        'slug'       => 'blog-understanding-retail-analytics',
        'title'      => 'Understanding Retail Analytics: 3 Reports You Must Run Every Week',
        'excerpt'    => 'Discover how analyzing your sales-by-item, customer purchase history, and supplier lead-times can unlock hidden profits in your retail store.',
        'date'       => '2026-07-03',
        'sort_order' => 1,
        'read_min'   => 5,
        'image'      => 'assets/img/blog-understanding-retail-analytics.jpg',
        'image_webp' => null,
        'alt'        => 'Laptop retail analytics reports',
    ],
];
